/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconCapAudioOff: typeof import('~icons/cap/audio-off.tsx')['default']
  const IconCapBgBlur: typeof import('~icons/cap/bg-blur.tsx')['default']
  const IconCapCheck: typeof import('~icons/cap/check.tsx')['default']
  const IconCapChevronDown: typeof import('~icons/cap/chevron-down.tsx')['default']
  const IconCapCircleCheck: typeof import('~icons/cap/circle-check.tsx')['default']
  const IconCapCirclePlus: typeof import('~icons/cap/circle-plus.tsx')['default']
  const IconCapCircleX: typeof import('~icons/cap/circle-x.tsx')['default']
  const IconCapCorners: typeof import('~icons/cap/corners.tsx')['default']
  const IconCapFile: typeof import('~icons/cap/file.tsx')['default']
  const IconCapFilmCut: typeof import('~icons/cap/film-cut.tsx')['default']
  const IconCapImage: typeof import('~icons/cap/image.tsx')['default']
  const IconCapInstant: typeof import('~icons/cap/instant.tsx')['default']
  const IconCapLayout: typeof import('~icons/cap/layout.tsx')['default']
  const IconCapLogo: typeof import('~icons/cap/logo.tsx')['default']
  const IconCapMessageBubble: typeof import('~icons/cap/message-bubble.tsx')['default']
  const IconCapMicrophone: typeof import('~icons/cap/microphone.tsx')['default']
  const IconCapMoreVertical: typeof import('~icons/cap/more-vertical.tsx')['default']
  const IconCapNext: typeof import('~icons/cap/next.tsx')['default']
  const IconCapPadding: typeof import('~icons/cap/padding.tsx')['default']
  const IconCapPause: typeof import('~icons/cap/pause.tsx')['default']
  const IconCapPauseCircle: typeof import('~icons/cap/pause-circle.tsx')['default']
  const IconCapPlay: typeof import('~icons/cap/play.tsx')['default']
  const IconCapPlayCircle: typeof import('~icons/cap/play-circle.tsx')['default']
  const IconCapPresets: typeof import('~icons/cap/presets.tsx')['default']
  const IconCapPrev: typeof import('~icons/cap/prev.tsx')['default']
  const IconCapRestart: typeof import('~icons/cap/restart.tsx')['default']
  const IconCapScissors: typeof import('~icons/cap/scissors.tsx')['default']
  const IconCapSettings: typeof import('~icons/cap/settings.tsx')['default']
  const IconCapShadow: typeof import('~icons/cap/shadow.tsx')['default']
  const IconCapStopCircle: typeof import('~icons/cap/stop-circle.tsx')['default']
  const IconCapStopwatch: typeof import('~icons/cap/stopwatch.tsx')['default']
  const IconCapTrash: typeof import('~icons/cap/trash.tsx')['default']
  const IconLucideSearch: typeof import('~icons/lucide/search.tsx')['default']
}
