packages:
  - "apps/recorder"
  - "apps/web"
  - "apps/storybook"
  - "packages/config"
  - "packages/env"
  - "packages/ui"
  - "packages/ui-solid"
  - "packages/utils"
  - "packages/web-api-contract"
  - "packages/web-api-contract-effect"
  - "packages/tsconfig"
